version: "{build}"

# Source Config

os: Visual Studio 2019

clone_folder: c:\gopath\src\github.com\assetchain\assetchain

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1

#init:
#  - git config --global core.autocrlf input
# Build

install:
  # Install the specific Go version.
  - set PATH=C:\go119\bin;%PATH%
  - set GOROOT=C:\go119
  - go version
  - go env
  # to check the where is mingw64 in env
  - dir C:\
  - dir C:\mingw-w64\
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\
  - dir C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
  #  - choco install bzr
  - set Path=C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\;%Path%
  - gcc --version
  - set path

build: false
deploy: false

test_script:
  - go env -w CGO_ENABLED=1
  - go build -buildmode=exe -o assetchain.exe
  - go build -buildmode=exe -o assetchain-cli.exe github.com/assetcloud/assetchain/cli
