# This is a basic workflow that is manually triggered
name: build linux-amd64

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push,pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    name: build_linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: checkout repo
        uses: actions/checkout@v2

      - name: compile binary
        run: make linux-amd64

      - name : Upload artifact bin
        uses: actions/upload-artifact@v2
        with:
          name: bityuan-linux-amd64.tar.gz
          path: |
            build/bityuan-linux-amd64.tar.gz
