# This is a basic workflow that is manually triggered
name: build linux-amd64

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push,pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    name: build_linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: compile binary
        run: make linux-amd64

      - name : Upload artifact bin
        uses: actions/upload-artifact@v2
        with:
          name: bityuan-linux-amd64.tar.gz
          path: |
            build/bityuan-linux-amd64.tar.gz
