name: build darwin-amd64
on: [push,pull_request]

jobs:
  build_macos:
    name: build_macos
    runs-on: macos-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: set go env
        run: export PATH=${PATH}:`go env GOPATH`/bin
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        run: make darwin-amd64

      - name : Upload artifact bin
        uses: actions/upload-artifact@v2
        with:
          name: bityuan-darwin-amd64.tar.gz
          path: |
            build/bityuan-darwin-amd64.tar.gz
